### ISSUE TITLE
downloads.7z

### ISSUE THREAD

**Issue by chalbin73** [DravenusRex/stalker-gamma-linux-guide#16]
Hi !

I closely followed the instructions on the GAMMA discord server, 
and when coming back to this guide when I was instructed to open the launcher, I noticed that I didn't have the `downloads.7z` file.
Weirdly on the discord instructions, step 7a is labeled as "REWORK IN PROGRESS, DON'T MIND THIS, GO ON" while showing
a gofile interface with a `downloads.7z` in it (https://gofile.io/d/mpDnsO).

It seems like the discord server does not instruct to download this 7zip file anymore ...
Is this normal ?

I'll still try with the file I found at https://gofile.io/d/mpDnsO.
Thank you very much !

**Comment by Siirko** [comment]
As I understand, ``downloads.7z`` is a backup of all addons needed, so you can just extract them in your GAMMA folder and it will be present in a ``downloads`` folder.

**Comment by chalbin73** [comment]
Yeah I realized that, I just thought that as the guide said "You should have : A GAMMA directory which contains the extracted contents of GAMMA RC3.7z and downloads.7z" It was required ... Thank you very much though !
