### ISSUE TITLE
Some minor conveniences.

### ISSUE THREAD

**Issue by cha0sbuster** [DravenusRex/stalker-gamma-linux-guide#3]
I'm going through the install process on a virtual machine right now, and I have both a hurdle to report and an insight I gained.

The hurdle was Visual C++ Redistributable; it's required for Mod Organizer 2 and can be obtained here: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 (A Windows user on a native machine would have this already.)

The insight is shared folders. I'm using virt-manager to install, and installing to an external USB drive, so I was able to use QEMU/KVM's USB Redirection to mount the drive in the VM for the install process, to avoid copying things around. But if you're installing with an internal drive, you'll need to use filesystem sharing, a tutorial for which is here:
https://blog.sergeantbiggs.net/posts/file-sharing-with-qemu-and-virt-manager/

Hope this helps someone a bit :)

**Comment by DravenusRex** [comment]
About the C++ Redistributable, is this not covered by the vcrun2019.dll that to be installed into the wineprefix, according to the guide? If anybody could clarify, that would be great.
As for the filesharing tutorial, I will take a look and see about linking that here in the guide. Thank you.
